### ISSUE TITLE
Bug: keybase avatar долго грузится

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#116]
Если зайти в https://dynamis-frontend-develop.herokuapp.com/main

то иногда видно, как долго грузится аватар.
И все это время видно следющее:

[![Screen Shot 2016-10-12 at 12.59.40.png](https://s17.postimg.org/kuypqv667/Screen_Shot_2016_10_12_at_12_59_40.png)](https://postimg.org/image/jsoj8bncr/)

**Comment by pitronalldak** [comment]
просто серое пространство оставил, попробовал спинер вставить внутрь аватара,  все мигать стало еще хуже..
