### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#132]
Смотри Deployment Scheme здесь - https://github.com/dynamisdao/dynamisapp

Там видно, что light wallet это то, что живет только в браузере (и никогда не попадает на бэкенд). В старом бэкенде это уже работает. Ты можешь посмотреть здесь - https://dynamisapp-develop.herokuapp.com/accounts/wallet/

Вот как это выглядит там:

[![Screen Shot 2016-10-18 at 18.38.28.png](https://s12.postimg.org/vexe2xu99/Screen_Shot_2016_10_18_at_18_38_28.png)](https://postimg.org/image/w4g6fausp/)

Идея вот в чем:
1) У нас есть Ethereum node вот здесь - http://52.16.72.86:8545 (можно пока этот адрес жестко зашить в код)
2) Если пользователь нажимает **Generate new wallet** -> генерируем ему новый кошелек. JSON для этого кошелька юзер может себе всегда скачать на тачку. Чтобы потом можно было зайти из другого браузера, например. Или с другой машины. Ну и просто как бэкап. Но этот JSON лучше никому не показывать, даже учитывая то, что он запаролен. Есть и кнопка **Upload your Wallet**
3) Чтобы отправить деньги куда-то юзер должен ввести адрес, кол-во и нажать Send Transaction. При этом браузер сам генерирует транзакцию и посылает RPC запрос нам на http://52.16.72.86:8545
Уже оттуда Ethereum node пишет транзакцию в сеть "деньги отправлены". 

Как-то так. Это чтобы ты понимал процесс.
Весь этот код работает, и ты можешь сам посмотреть, как он написан в старом репозитории. Тебе нужно будет просто взять его оттуда.
## В новом фронте нам нужно

[![Screen Shot 2016-10-18 at 19.21.48.png](https://s21.postimg.org/gkuzaz2t3/Screen_Shot_2016_10_18_at_19_21_48.png)](https://postimg.org/image/e3j83piwj/)

По нажатию мы должны открывать окно стандартного для нас вида - 
[![smart_deposit_new.jpg](https://s18.postimg.org/3yp7lxjjt/smart_deposit_new.jpg)](https://postimg.org/image/rcx6xv1h1/)
### Если кошелька сейчас нет созданного:
- Generate New Wallet
- Upload Wallet

по нажатию на Generate New Wallet -> должна происходить валидация всех полей и выскакивать диалог с вопросом "Please enter your Password" 
### Eсли кошелек уже есть прогруженный:
- Generate New Wallet
- Download Your Wallet
- To address
- Amount
- Send Transaction  

по нажатию на Send Transaction -> должна происходить валидация всех полей и выскакивать диалог с вопросом "Please enter your Password" .
### p.s.

Там еще есть кнопка Buy 1 Immature token, но это пока делать **НЕ НУЖНО**

**Comment by pitronalldak** [comment]
Сделал частично, посмотри как это выглядит, сейчас пока что не рабатет кнопка оплатить! и не совсем понятно что должно происходит если новый wallet пользователь захочит сгенерить, уже находясь в старом(вопрос про UI).

**Comment by AnthonyAkentiev** [comment]
1) ок, посмотрю сейчас.
2) новый можно генерить конечно. лучше предупреждать, что уже есть один. чтобы перетереть просто поверх и все.
