### ISSUE TITLE
Policy is in state 'submitted' -> go to /policy

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#134]
1) Create new policy
2) Sign it. Works as expected
3) Log out
4) Log in again

Result:
We are in /main

[![Screen Shot 2016-10-18 at 22.31.00.png](https://s17.postimg.org/9kqlv020v/Screen_Shot_2016_10_18_at_22_31_00.png)](https://postimg.org/image/6qnghjzuj/)

But must be in /policy

**Comment by pitronalldak** [comment]
Все таки, надо либо чтобы с policy, при логине приходило сразу поле, подписан policy или нет. Или делать заглушку с прогрес лоадером, на время пока второй запрос обрабатывается. А то получается мигание на разные страницы и ничего с ним не поделать((

**Comment by AnthonyAkentiev** [comment]
2 запроса отправлять сильно дольше, чем один. Ну пусть юзер подождет, а все контролы будут задисейблены) Не хочется поле добавлять просто для "оптимизации". Потом у нас будет много полиси у одного юзера, и не понятно что с этим делать будем...
