### ISSUE TITLE
Remove these links from starting screen

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#138]
[![Screen Shot 2016-10-19 at 01.23.34.png](https://s16.postimg.org/48dzdsmw5/Screen_Shot_2016_10_19_at_01_23_34.png)](https://postimg.org/image/wl9h498m9/)

**Comment by pitronalldak** [comment]
Удалить ссылки, или вообще две колонки удалить?

**Comment by AnthonyAkentiev** [comment]
Вообще эти 2 колонки удалить. Без логина все-равно смысла в них нет никакого...
