### ISSUE TITLE
'Verification task' - submit

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#140]
See 137 and 139 tasks.
When user clicks on 'Submit' -> please call this method: http://docs.dynamis1.apiary.io/#reference/0/peer-review-tasks/submit-peer-review

**Comment by pitronalldak** [comment]
Надо что-то делать со списком verification tasks, или передергивать рест или удалять из списка подписанный просто на фронте... Чтобы удаленного в списке не было...

**Comment by AnthonyAkentiev** [comment]
Подписанного в списке быть не должно...Сейчас скажу Алексею.
