### ISSUE TITLE
'Verification task' screen - fix layout

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#143]
Мне кажется, что верстка будет лучше, если расположить все элементы вертикально один под другим. 
Сейчас не очень понятно где какое поле:

[![Screen Shot 2016-10-24 at 11.23.16.png](https://s10.postimg.org/753845uax/Screen_Shot_2016_10_24_at_11_23_16.png)](https://postimg.org/image/bqzcciftx/)

1) Желательно всю эту панель сделать больше по высоте, чтобы все влезло
2) По умолчанию должно быть выбрано 'verify'
3) please sign this невозможно выделить мышкой, чтобы скопировать

**Comment by pitronalldak** [comment]
Про мышку оч странно,видимо разные chrome, раздизайблю...

**Comment by AnthonyAkentiev** [comment]
Спасибо
