### ISSUE TITLE
Wallet - 'Generate new wallet' - add dialog instead of field

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#146]
'Generate new wallet' 

1) Go to wallet
2) Click on 'Generate new wallet'
Result:

[![Screen Shot 2016-10-24 at 15.09.04.png](https://s12.postimg.org/4rozt6m4t/Screen_Shot_2016_10_24_at_15_09_04.png)](https://postimg.org/image/cx71rcadl/)

BUT Must show dialog, not a field...

То есть должен выскакивать диалог с вопросом, а не поле открываться. Поле - не очень хорошо с точке зрения UX. 
Получается он должен нажимать 2 раза на одну и ту же кнопку. 
А должно быть так:
1) Нажал Generate
2) Показался диалог
3) Ввел туда желаемый пароль
4) Нажал ОК
5) Кошелек сгенерился

**Comment by pitronalldak** [comment]
Под диалогом ты подразумеваешь модалку?

**Comment by AnthonyAkentiev** [comment]
Да
