### ISSUE TITLE
Policy application: use new fields in API

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#160]
http://docs.dynamis1.apiary.io/#reference/0/policies/update-policy

```
        "requestedPremiumAmount": 12,

        "requestedCoverageAmount": 84,
        "requestedDuration": 4
```

These fields are here:

[![Screen Shot 2016-10-27 at 13.44.57.png](http://s18.postimg.org/7hsy8rkbd/Screen_Shot_2016_10_27_at_13_44_57.png)](http://postimg.org/image/c3p2h45ud/)

**Comment by pitronalldak** [comment]
А откуда взять "requestedDuration", вроде нигде не вводим покрытие....

**Comment by AnthonyAkentiev** [comment]
Просто пока поставь значение из фронта

**Comment by pitronalldak** [comment]
ок
