### ISSUE TITLE
Wallet: Upload/Download your wallet buttons

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#165]
Must work just like in old frontend

**Comment by pitronalldak** [comment]
А если у пользователя уже есть wallet,  а он хочет загрузить  новый, его надо предупредить что он перетрет старый?... Просто  либа с wallet  позволяет список из нескольких wallet хранить....

**Comment by AnthonyAkentiev** [comment]
Нужно задавать вопрос и "перетирать последний".
