### ISSUE TITLE
Smart deposit - add modal Message Box

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#175]
1) Go to Smart Deposit
2) Click on 'pay'
3) Transaction is sent...

TODO:
Show modal Message Box (not a popup!) with:

1) TX Hash
2) text "Send succeeded. Please wait for the transaction to be proceeded by us. It will take about 1-2 minutes"
3) OK button

**Comment by pitronalldak** [comment]
tсли оплата прошла,  должно работать корректно, толко потестить не смог, деньжат нет. Можешь пожалуйста на юзаре 22@22.ru тестовых денег скинуть...

**Comment by AnthonyAkentiev** [comment]
Мне нужен твой адрес кошелька. Скину, конечно
