### ISSUE TITLE
Bug: coverage -> history_form

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#86]
1) Ввожу данные о работе 
2) Нажимаю Complete Section
3) Перехожу в coverage
4) нажимаю F5 -> оказываюсь опять в history_form, но там пусто (((

точно так же, если перейти в последний экран (sign)

https://dynamis-frontend-develop.herokuapp.com/history-form-1

[![Screen Shot 2016-10-04 at 13.44.53.png](https://s21.postimg.org/qbvc6w35j/Screen_Shot_2016_10_04_at_13_44_53.png)](https://postimg.org/image/xrulsoqur/)

**Comment by pitronalldak** [comment]
Теперь все храним в браузере...
