### ISSUE TITLE
Bug: login:107

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#92]
login:107 Uncaught TypeError: Cannot read property '__reactInternalInstance$vjj1gosexv4p1npknlcj46lxr' of null

1) Login 123@123.ru
123456

2) Account has no 'keybase'. Maybe because of this...

[![Screen Shot 2016-10-05 at 12.05.57.png](https://s13.postimg.org/g47kb5rev/Screen_Shot_2016_10_05_at_12_05_57.png)](https://postimg.org/image/iyapoltkz/)

**Comment by pitronalldak** [comment]
Dозможно потому что у этого мыла нет keybase_username, у нас вроде не может такой пользователь зарегаться, и это единственное уникальное название кроме мыла, которое мне приходит в userInfo

**Comment by AnthonyAkentiev** [comment]
Давай тогда временно отложим. Переношу в Backlog
