### ISSUE TITLE
Main Policy Screen: policy в состояниях Init и Submitted

### ISSUE THREAD

**Issue by AnthonyAkentiev** [dynamisdao/frontend2#95]
[![Screen Shot 2016-10-06 at 14.23.18.png](https://s22.postimg.org/y5ao2fz69/Screen_Shot_2016_10_06_at_14_23_18.png)](https://postimg.org/image/oxiflqs3x/)

Можно посмотреть, как это работает на старом фронте:
https://dynamisapp-develop.herokuapp.com/accounts/my-policy/

метод http://docs.dynamis1.apiary.io/#reference/0/policies/get-policy

поле **state**
# Если полиси в состоянии Init

**на правой панели**
1. Показывать поле 'Policy #'
2. Показывать поле Status: Incomplete
3. Показывать кнопку Edit -> должен быть переход к редактированию policy (переход на history-form)
# Если полиси в состоянии Submitted

**на правой панели**
1. Показывать поле 'Policy #'
2. Показывать поле Status: Waiting for Smart Deposit
3. Показывать кнопку Pay Smart Deposit -> должен быть переход в окно "Smart Deposit" (смотри таск 96)

**Comment by pitronalldak** [comment]
Пока что всегда в состоянии Status: Waiting for Smart Deposit, чтобы дальше можно было тестить, не проставляя в БД ничего, также везде добавил спинеры, чтобы не было никакого компонент....

**Comment by AnthonyAkentiev** [comment]
ок
